Add Scheduler
lnbits/lnbits-extensions pull request #263
Opened 2024-02-02 12:29 UTC by arcbtc

2024-02-02 13:07 UTC, arcbtc commented
Issue with logo, I think its the size

2024-07-12 18:32 UTC, bitkarrot commented
@dni @arcbtc bump.

2024-07-26 22:05 UTC, bitkarrot commented
updated Scheduler to fix the install error. asking people to test it now on 0.12.10 and 0.12.11

will also check the updates @dni made to decoder and mirror to scheduler

2024-07-31 07:23 UTC, bitkarrot reviewed
I can't seem to edit this PR so made some comments on what needs to be updated.

2024-07-31 07:23 UTC, bitkarrot commented on extensions.json
> +            "version": "0.1.1",
update to version v0.1.2-alpha-2

2024-07-31 07:23 UTC, bitkarrot commented on extensions.json
> +            "min_lnbits_version": "0.12.0",
min version 0.12.10

2024-07-31 07:23 UTC, bitkarrot commented on extensions.json
> +            "hash": "db7470dc51a4d8bf3c0e3da49d6dd37bd584f60302778682165ce359d327e06c"
f02fab0c1b0d6a6f2909a47e2d1692ae8900b1f0d1e4aeb7782585f8a664d7c0

2024-07-31 07:23 UTC, bitkarrot commented on extensions.json
> +            "archive": "https://github.com/bitkarrot/scheduler/archive/refs/tags/v0.1.1.zip",
https://github.com/bitkarrot/scheduler/archive/refs/tags/v0.1.2-alpha-2.zip

2024-07-31 07:23 UTC, bitkarrot commented
@arcbtc

2024-08-11 20:33 UTC, prusnak commented
updated to  0.1.2-alpha-2 like @bitkarrot suggested

2024-08-11 20:39 UTC, prusnak approved these changes

2024-09-03 17:58 UTC, bitkarrot commented
LFG!!!

2024-09-03 19:50 UTC, dni requested changes
```"version": "0.1.2-alpha-2",```
why this weird version?

2024-09-03 19:57 UTC, bitkarrot commented
the only thing that changed in there was min version lnbits. 

would you be feel better if i named it v0.1.3? we can make another release and just rename it. LMK

@dni

2024-09-03 20:16 UTC, dni commented
> the only thing that changed in there was min version lnbits.
> 
> would you be feel better if i named it v0.1.3? we can make another release and just rename it. LMK
> 
> @dni

yes please :)

2024-09-24 07:25 UTC, motorina0 approved these changes

2024-09-24 07:52 UTC, prusnak commented on extensions.json
> +            "version": "0.1.2-alpha-2",
```suggestion
            "version": "0.1.3",
```

2024-09-24 07:52 UTC, prusnak commented on extensions.json
> +            "archive": "https://github.com/bitkarrot/scheduler/archive/refs/tags/v0.1.2-alpha-2.zip",
```suggestion
            "archive": "https://github.com/bitkarrot/scheduler/archive/refs/tags/v0.1.3.zip",
```

2024-09-24 07:52 UTC, prusnak commented on extensions.json
> +            "hash": "f02fab0c1b0d6a6f2909a47e2d1692ae8900b1f0d1e4aeb7782585f8a664d7c0"
```suggestion
            "hash": "8d152c00371f001ed9712be1b265f5ff9900066fc78707e79fec24302151bbde"
```

2024-09-24 08:00 UTC, prusnak commented
I updated the PR to latest version 0.1.3 but now the jmeter test fails - can you please @motorina0 have a look?

2024-09-24 08:13 UTC, prusnak commented
Thanks @motorina0, now all tests are green.

@dni will you give us a green review since your request to change the version has been addressed, so we can push this through?

2024-09-24 08:18 UTC, dni approved these changes

2024-09-24 08:18 UTC, merged