[UPDATE] nostrnip5 to v0.2.6
lnbits/lnbits-extensions pull request #398
Opened 2024-08-07 14:28 UTC by alanbits

https://github.com/lnbits/nostrnip5/releases/v0.2.6

2024-08-11 20:44 UTC, prusnak requested changes

2024-08-11 20:44 UTC, prusnak commented on extensions.json
>              "min_lnbits_version": "0.12.5",
```suggestion
            "min_lnbits_version": "0.12.9",
```

2024-08-11 20:50 UTC, prusnak approved these changes

2024-08-30 04:12 UTC, dni approved these changes

2024-08-30 04:12 UTC, merged